# Generated by Django 3.2 on 2022-11-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_auto_20221111_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Disabled', 'Disabled'), ('Deleted', 'Deleted')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Disabled', 'Disabled'), ('Deleted', 'Deleted')], default='Pending', max_length=255),
        ),
    ]
