# Generated by Django 3.2 on 2022-11-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_auto_20221111_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Verified'), ('3', 'Disabled'), ('4', 'Deleted'), ('5', 'Enabled')], default='1', max_length=255),
        ),
    ]
